In [1]:
from transformers import RobertaTokenizer, TFRobertaModel
tokenizer = RobertaTokenizer.from_pretrained('roberta-base')
model = TFRobertaModel.from_pretrained('roberta-base')
text = "Replace me by any text you'd like."
encoded_input = tokenizer(text, return_tensors='tf')
output = model(encoded_input)


c:\Users\BS6517\Documents_local\projet_6\oc_projet_6\.venv\Lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFRobertaModel: ['roberta.embeddings.position_ids', 'lm_head.dense.bias', 'lm_head.layer_norm.bias', 'lm_head.dense.weight', 'lm_head.layer_norm.weight', 'lm_head.bias']
- This IS expected if you are initializing TFRobertaModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFRobertaModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
Some weights or buffers of the TF 2.0 model TFRobertaModel were not initialized from the PyTorch model and are newly initialized: ['roberta.pooler.dense.weight', 'roberta.pooler.dense.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and infe

In [2]:
output

TFBaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=<tf.Tensor: shape=(1, 12, 768), dtype=float32, numpy=
array([[[-0.11464329,  0.11033368, -0.01485654, ..., -0.0808996 ,
         -0.00180649, -0.02707545],
        [-0.02248313,  0.16116914,  0.05555476, ...,  0.5365964 ,
          0.11962052,  0.15758018],
        [ 0.05315702, -0.00201608,  0.03704339, ..., -0.48868644,
          0.16412757,  0.27361882],
        ...,
        [-0.15857415,  0.08374347,  0.13017938, ...,  0.39700964,
          0.17148274, -0.08482099],
        [-0.1065264 ,  0.10436887, -0.03831965, ..., -0.10680677,
         -0.00145985, -0.0516791 ],
        [ 0.00592976,  0.07583912,  0.12279624, ...,  0.10374916,
          0.00748072,  0.09762412]]], dtype=float32)>, pooler_output=<tf.Tensor: shape=(1, 768), dtype=float32, numpy=
array([[-2.20398039e-01,  4.69886698e-03, -1.94691941e-01,
        -2.02388555e-01, -1.08215801e-01,  2.00719774e-01,
        -5.99835813e-02,  1.79560125e-01,  2.39713296e-